apiVersion: v1
kind: Service
metadata:
  name: lgtm
spec:
  selector:
    app: lgtm-grafana
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80 # The port the load balancer exposes
      targetPort: 3000 # The port Grafana runs on
