apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: keycloak-route
spec:
  parentRefs:
    - name: traefik
      sectionName: websecure
  hostnames:
    - "keycloak.learning.localhost.com"
  rules:
    - backendRefs:
        - name: keycloak-learning-service
          port: 8080
